### ISSUE TITLE
Help wanted in dumping real ROM of fx-570VN PLUS

### ISSUE THREAD

**Issue by gamingwithevets** [user202729/fxesplus#2]
Dear user,

I saw your fx-570ES PLUS VerE dump hackstring on UCF, and managed to port the segment 0 hackstring to the fx-570VN PLUS.
Unfortunately, I need a program to analyze the video, and I don't have that at the moment. So can you send it?
If it's in this repository, where is it? I can't seem to find it.

Also, there's a Casio calculator hacking Discord server, if you have Discord you can join.
http://discord.gg/QjGpH6rSQQ

Thanks in advance!

**Comment by user202729** [comment]
Technically it's at https://github.com/user202729/lcdreader-img , but I forgot how to use it myself. (and looks like documentation is sparse)
